default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ysports
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
